### ISSUE TITLE
Crash when exiting atom

### ISSUE THREAD

**Issue by julianveerkamp** [simurai/one-vibrancy#16]
Whenever I exit Atom a crash occurs, but only if the one-vibrancy Plugin is installed.  
It doesn't matter if I exit via CMD+Q or use the Red-X.  
Happens on both macOS 10.14 and 10.13.6  
This is particularly annoying since I have to reopen every Project again, after Exiting Atom.

**Comment by simurai** [comment]
Yes, I can reproduce this too. Reloading Atom with `one-vibrancy` enabled causes Atom to crash. I wonder what changed?

**Comment by julianveerkamp** [comment]
I’ve also read that Electron has some issues with vibrancy, but I’m not sure if those issues are connected to this one.

**Comment by scherii** [comment]
@simurai It might be [electron version 2](https://github.com/atom/atom/commit/09cbcbe9e3b44f60b65c5c47d9d06cffa126d995) that caused the macOS vibrancy related crashes. And it seems that https://github.com/atom/atom/issues/17819 will fix it. I couldn't get my atom build to run yet to verify this though.

**Comment by simurai** [comment]
> @scherii It might be electron version 2 that caused the macOS vibrancy related crashes. 

Yeah, sounds like this issue: https://github.com/electron/electron/issues/12068. Should be fixed in Electron 3.0. But not sure when it lands in Atom.

**Comment by scherii** [comment]
I just built the latest [Atom from electron-3-0 branch](https://github.com/atom/atom/tree/electron-3-0) on macOS 10.14.2 and can confirm that vibrancy works again.

![image](https://user-images.githubusercontent.com/946853/50509566-b29c6480-0a86-11e9-900e-9d8581a11f15.png)

**Comment by HansJK** [comment]
Since Atom is still using Electron 2.0.16, this plugin dosen't work? Because it will still crash the newest version of Atom. Might be a good idea to put a disclaimer in the Readme.

**Comment by julianveerkamp** [comment]
This appears to be fixed in Atom version 1.39.1
